### ISSUE TITLE
Seems to try to set build-status to running twice

### ISSUE THREAD

**Issue by ananace** [Argelbargel/gitlab-branch-source-plugin#26]
Got another strange issue for you to look at, though this one seems to be very rare - only happens for a single project for us.

`jenkins.log` reports;

```
Jun 29, 2017 4:05:16 PM argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator visitSources
INFO: visiting sources for context GitLab...
Jun 29, 2017 4:05:17 PM argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator visitSources
INFO: visiting sources for context GitLab...
Jun 29, 2017 4:05:19 PM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: GitLab/group%2Fproject #20170629.160518 branch indexing action completed: SUCCESS in 1.2 sec
Jun 29, 2017 4:05:22 PM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: GitLab/group%2Fproject #20170629.160521 branch indexing action completed: SUCCESS in 0.99 sec
Jun 29, 2017 4:05:30 PM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: GitLab/group%2Fproject #20170629.160529 branch indexing action completed: SUCCESS in 0.84 sec
Jun 29, 2017 4:05:32 PM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: GitLab/group%2Fproject #20170629.160531 branch indexing action completed: SUCCESS in 0.81 sec
Jun 29, 2017 4:05:43 PM argelbargel.jenkins.plugins.gitlab_branch_source.actions.GitLabSCMBuildStatusPublisher$Message run
SEVERE: failed to set build-status of '#2 Syntax Validation' for project 412 to running
javax.ws.rs.BadRequestException: HTTP 400 Bad Request
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:197)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
        at com.sun.proxy.$Proxy84.changeBuildStatus(Unknown Source)
        at argelbargel.jenkins.plugins.gitlab_branch_source.actions.GitLabSCMBuildStatusPublisher$Message.run(GitLabSCMBuildStatusPublisher.java:94)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

Jun 29, 2017 4:06:00 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: GitLab/group%2Fproject/testing #108 completed: UNSTABLE
```

The logger for `com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder` meanwhile reports;

```
Jun 29, 2017 4:05:43 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: POST
URL: https://gitlab.fqdn/api/v3/projects/412/statuses/9d80b8f0d9695aeab22c8c438f0c808db64b4341
Request headers: [
Accept = [application/json],
Content-Type = [application/x-www-form-urlencoded],
PRIVATE-TOKEN = [****FILTERED****]
]

Jun 29, 2017 4:05:43 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://gitlab.fqdn/api/v3/projects/412/statuses/9d80b8f0d9695aeab22c8c438f0c808db64b4341
Status: 201 Created
Response headers: [
Cache-Control = [max-age=0, private, must-revalidate],
Connection = [Keep-Alive],
Content-Length = [597],
Content-Type = [application/json],
Date = [Thu, 29 Jun 2017 14:05:43 GMT],
Etag = [W/"f2a8c46b42bbaddb9ab30cab0548282f"],
Keep-Alive = [timeout=15, max=90],
Server = [Apache/2.4.6 (CentOS)],
Strict-Transport-Security = [max-age=31536000;includeSubdomains],
Vary = [Origin],
Via = [1.1 lusitania],
X-Frame-Options = [SAMEORIGIN],
X-Request-Id = [3e0f2d9f-2c16-42cc-a407-ebd862fe30ae],
X-Runtime = [0.051826]
]
Response body: {
  "id" : 42760,
  "sha" : "9d80b8f0d9695aeab22c8c438f0c808db64b4341",
  "ref" : "testing",
  "status" : "success",
  "name" : "#1 Source Preparation",
  "target_url" : "https://jenkins.fqdn/job/GitLab/job/group%252Fproject/job/testing/68/",
  "description" : null,
  "created_at" : "2017-06-29T14:05:25.317Z",
  "started_at" : "2017-06-29T14:05:25.341Z",
  "finished_at" : "2017-06-29T14:05:43.800Z",
  "allow_failure" : false,
  "coverage" : null,
  "author" : {
    "name" : "Jenkins",
    "username" : "jenkins",
    "id" : 5,
    "state" : "active",
    "avatar_url" : "https://gitlab.fqdn/uploads/system/user/avatar/5/logo.png",
    "web_url" : "https://gitlab.fqdn/jenkins"
  }
}

Jun 29, 2017 4:05:43 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: POST
URL: https://gitlab.fqdn/api/v3/projects/412/statuses/9d80b8f0d9695aeab22c8c438f0c808db64b4341
Request headers: [
Accept = [application/json],
Content-Type = [application/x-www-form-urlencoded],
PRIVATE-TOKEN = [****FILTERED****]
]

Jun 29, 2017 4:05:43 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://gitlab.fqdn/api/v3/projects/412/statuses/9d80b8f0d9695aeab22c8c438f0c808db64b4341
Status: 400 Bad Request
Response headers: [
Cache-Control = [no-cache],
Connection = [close],
Content-Length = [111],
Content-Type = [application/json],
Date = [Thu, 29 Jun 2017 14:05:43 GMT],
Server = [Apache/2.4.6 (CentOS)],
Strict-Transport-Security = [max-age=31536000;includeSubdomains],
Vary = [Origin],
Via = [1.1 lusitania],
X-Frame-Options = [SAMEORIGIN],
X-Request-Id = [d2411079-3235-4367-9f4a-7e172a27c33d],
X-Runtime = [0.041666]
]
Response body: {
  "message" : "Cannot transition status via :run from :running (Reason(s): Status cannot transition via \"run\")"
}
```

**Comment by oxygenxo** [comment]
Hi,
I see the same message when using Jenkins GitLab plugin. I'm afraid that the problem is in GitLab API... it doesn't allow to set status on the same commit twice. We're facing it when trying to call 'Jenkins please retry the build' functionality
