### ISSUE TITLE
Build status publishing broken with gitlab-plugin 1.5.0+

### ISSUE THREAD

**Issue by ananace** [Argelbargel/gitlab-branch-source-plugin#46]
```
Nov 01, 2017 9:54:18 AM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
SEVERE: A thread (pool-19-thread-54/5008) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NoSuchMethodError: com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.getClient(Ljava/lang/String;)Lcom/dabsquared/gitlabjenkins/gitlab/api/GitLabApi;
        at argelbargel.jenkins.plugins.gitlab_branch_source.actions.GitLabSCMBuildStatusPublisher$Message.getClient(GitLabSCMBuildStatusPublisher.java:107)
        at argelbargel.jenkins.plugins.gitlab_branch_source.actions.GitLabSCMBuildStatusPublisher$Message.run(GitLabSCMBuildStatusPublisher.java:90)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Most likely related to the return type change from jenkinsci/gitlab-plugin#614

**Comment by Argelbargel** [comment]
@ace13: could you give [0.6.6](https://github.com/Argelbargel/gitlab-branch-source-plugin/releases/tag/0.6.6) a try? This release is built against the current version of the gitlab-plugin...

**Comment by ace13** [comment]
Thanks for the reminder about this btw, works fine on here as well
