### ISSUE TITLE
Ignore SSL Certificate Errors does not work when scanning GITLAB

### ISSUE THREAD

**Issue by smutel** [Argelbargel/gitlab-branch-source-plugin#47]
Hello,

I think that I have setup this module correctly but ...

 I have a strange behavior. When I go to the GITLAB configuration (in Configure System), I have the error message : "API Token for Gitlab access required". However the credentials is correctly setup and I click on "TEST connection" button and the result is SUCCESS.

I am not able to scan projects. Here are the message displayed during the scan:

> Started by user Mutel, Samuel
> [Fri Nov 10 05:28:18 EST 2017] Starting organization scan...
> [Fri Nov 10 05:28:18 EST 2017] Updating actions...
> [Fri Nov 10 05:28:18 EST 2017] Consulting GitLab Projects
> Retrieving projects for CIO GITLAB...
> [Fri Nov 10 05:28:18 EST 2017] Finished organization scan. Scan took 5 ms
> Finished: NOT_BUILT

Any idea of what's wrong?
Thanks.

**Comment by smutel** [comment]
Same issue with 0.7-dev. Any idea?

**Comment by smutel** [comment]
- In the global configuration I select "Ignore SSL Certificate Errors".
- However the scan is not working with messages below:
> building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by Argelbargel** [comment]
@smutel: i've updated the dev-branch (see [0.7.1-dev](https://github.com/Argelbargel/gitlab-branch-source-plugin/releases/tag/0.7.1-dev)) and the release branch (see [0.6.6.2](https://github.com/Argelbargel/gitlab-branch-source-plugin/releases/tag/0.6.6.2)) so that the internal api used for those api-calls which gitlab-plugin does not have.

Both versions should now respect the setting of "Ignore SSL Certificate Errors"

**Comment by smutel** [comment]
OK. Thanks. It seems to work now.
I encounter other issues with 0.7.2-dev:

> could not register hook https://jenkins/gitlab-scm/notify/6de60fc0e8f4eb36f5455bce3ae3d3b2: error accessing gitlab-api: Read timed out

> Executor threw an exception
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:327)
	at org.gitlab.api.http.GitlabHTTPRequestor.access$200(GitlabHTTPRequestor.java:28)
	at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:232)
Caused: java.lang.Error
	at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:239)
	at org.gitlab.api.http.GitlabHTTPRequestor$1.hasNext(GitlabHTTPRequestor.java:193)
	at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:161)
	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.findProjects(GitLabAPI.java:165)
	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.findProjects(GitLabAPI.java:160)
	at argelbargel.jenkins.plugins.gitlab_branch_source.DefaultProjectQuery.execute(DefaultProjectQuery.java:18)
	at argelbargel.jenkins.plugins.gitlab_branch_source.ProjectQuery.execute(ProjectQuery.java:56)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:32)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:25)
	at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator.visitSources(GitLabSCMNavigator.java:133)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:459)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:910)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)

**Comment by Argelbargel** [comment]
Please try [0.7.3-dev](https://github.com/Argelbargel/gitlab-branch-source-plugin/releases/tag/0.7.3-dev)...

**Comment by smutel** [comment]
Works better thanks.
Now I think that I have the bug #38.
The checkout credentials are not populated in each project configuration.

> stderr: fatal: Authentication failed for 'https://git/CIO/test2.git/'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1970)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1689)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:380)
	at jenkins.plugins.git.GitSCMFileSystem$BuilderImpl.build(GitSCMFileSystem.java:394)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:301)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:100)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:263)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Finished: FAILURE

**Comment by Argelbargel** [comment]
Ok. Then i'll close here.
