### ISSUE TITLE
Builds completely broken on 0.6.6.2

### ISSUE THREAD

**Issue by ananace** [Argelbargel/gitlab-branch-source-plugin#48]
```
retrieving head-revision for production
argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPIException: error accessing gitlab-api: Read timed out
	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.getBranch(GitLabAPI.java:104)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveBranchRevision(SourceHeads.java:102)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveRevision(SourceHeads.java:90)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieve(SourceHeads.java:77)
	at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMSource.retrieve(GitLabSCMSource.java:256)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:564)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:95)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:263)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Finished: FAILURE
```

Downgraded to 0.6.6.1 and it seems to work fine on there.

**Comment by Argelbargel** [comment]
Damn! I. Need. Tests :-/

**Comment by Argelbargel** [comment]
Okay, let's try [0.6.6.3](https://github.com/Argelbargel/gitlab-branch-source-plugin/releases/tag/0.6.6.3)...

**Comment by ace13** [comment]
Exact same error with 0.6.6.3 too, and I noticed that it fails to acquire listeners as well

```
Nov 21, 2017 7:17:48 PM argelbargel.jenkins.plugins.gitlab_branch_source.hooks.HookManager$ListenerState acquire                         
INFO: acquiring listener for GitLab/user%2FWorkflow-Libs...                                                                           
Nov 21, 2017 7:17:48 PM argelbargel.jenkins.plugins.gitlab_branch_source.hooks.HookManager registerHook                                  
INFO: registering project-hook for 525018ff09dde899935859cac6d53bbf/543...
Nov 21, 2017 7:17:48 PM argelbargel.jenkins.plugins.gitlab_branch_source.hooks.HookManager registerHook                                  
WARNING: could not register hook https://jenkins/gitlab-scm/notify/525018ff09dde899935859cac6d53bbf/543: error accessing gitlab-api: Read timed out
```

**Comment by Argelbargel** [comment]
Hrmpf! [0.6.6.4](https://github.com/Argelbargel/gitlab-branch-source-plugin/releases/tag/0.6.6.4)...

**Comment by ace13** [comment]
Builds seem to be working again, but I still see a few failed hook registrations in the log. Quite a lot of successful ones too though.

**Comment by Argelbargel** [comment]
Strange. Are you still getting read-timeout for the failing registrations=. This change now only sets whether certificate-errors get ignored or not so it should use the default read-timeout as with 0.6.6.1.

**Comment by ace13** [comment]
Maybe related to the sheer number of registrations that Jenkins does on
launch, got over 200 projects through it after all

**Comment by Argelbargel** [comment]
Can you check whether the timeout occured before you upgraded to 0.6.6.2?

**Comment by ace13** [comment]
I'll try to check once I have time
