### ISSUE TITLE
Scan for GitLab projects fails with a 403 error

### ISSUE THREAD

**Issue by ace13** [Argelbargel/gitlab-branch-source-plugin#5]
The scan seems to die on the same project every time, where Jenkins user is a developer on the project in question - which is also a public project.

![Project settings](https://cloud.githubusercontent.com/assets/534460/23511322/fc473704-ff5c-11e6-8f9e-bc276c60fbc5.png)
![Member list](https://cloud.githubusercontent.com/assets/534460/23511323/fc7e417c-ff5c-11e6-877b-95dbc0a2bc01.png)

So the likely culprit could very well be the fact that a rate limit is hit at that point, which seems very likely - considering we have over 250 potential projects for it to scan.

The exact block of errors is;
```
error retrieving projects for gitlab.example.com: argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPIException: error accessing gitlab-api: Forbidden

ERROR: [Thu Mar 02 15:14:37 CET 2017] Could not fetch sources from navigator argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator@5973db21
argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPIException: error accessing gitlab-api: Forbidden

	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.getBranches(GitLabAPI.java:79)
	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.getBranches(GitLabAPI.java:72)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveBranches(SourceHeads.java:188)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveAll(SourceHeads.java:163)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieve(SourceHeads.java:69)
	at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMSource.retrieve(GitLabSCMSource.java:245)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:300)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:254)
	at jenkins.branch.MultiBranchProjectFactory$BySCMSourceCriteria.recognizes(MultiBranchProjectFactory.java:263)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.recognizes(OrganizationFolder.java:1266)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1281)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitProject(SourceVisitor.java:70)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:39)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:27)
	at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator.visitSources(GitLabSCMNavigator.java:381)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:399)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:219)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:154)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:850)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://gitlab.example.com/api/v3/projects/250/repository/branches/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:327)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:144)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:116)
	at org.gitlab.api.GitlabAPI.getBranches(GitlabAPI.java:1263)
	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.getBranches(GitLabAPI.java:77)
	... 20 more
[Thu Mar 02 15:14:37 CET 2017] Finished organization scan. Scan took 49 sec
FATAL: Failed to recompute children of Gitlab
argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPIException: error accessing gitlab-api: Forbidden

	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.getBranches(GitLabAPI.java:79)
	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.getBranches(GitLabAPI.java:72)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveBranches(SourceHeads.java:188)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveAll(SourceHeads.java:163)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieve(SourceHeads.java:69)
	at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMSource.retrieve(GitLabSCMSource.java:245)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:300)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:254)
	at jenkins.branch.MultiBranchProjectFactory$BySCMSourceCriteria.recognizes(MultiBranchProjectFactory.java:263)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.recognizes(OrganizationFolder.java:1266)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1281)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitProject(SourceVisitor.java:70)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:39)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:27)
	at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator.visitSources(GitLabSCMNavigator.java:381)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:399)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:219)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:154)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:850)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://gitlab.example.com/api/v3/projects/250/repository/branches/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:327)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:144)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:116)
	at org.gitlab.api.GitlabAPI.getBranches(GitlabAPI.java:1263)
	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.getBranches(GitLabAPI.java:77)
	... 20 more
Finished: FAILURE
```

**Comment by ace13** [comment]
I think I've all but confirmed the fact that it's a rate-limit being hit now, no query is allowed by the Jenkins user anymore.

**Comment by Argelbargel** [comment]
Ouch :-/ Sorry! 
I'll try to find out how to rate-limit the api-calls. But the documentation is very sparse here. 

Could you check which paths are protected by rack-attack in your gitlab-server? They are configured in /etc/gitlab/gitlab.rb:

'''
# gitlab_rails['rack_attack_protected_paths'] = [
# <paths>
# ]
'''
In my default-installation only api/.../session is protected and if i understand the generated  /opt/gitlab/embedded/service/gitlab-rails/config/initializers/rack_attack.rb correctly only post requests are checked. As we authenticate via private token sent by http-header and thus do not create a session and only use get requests there should be no rate-limiting at all. Well, i'll try to find more information on that...

For now the only workaround seems to try to loosen the rate-limiting in gitlab for your jenkins server (not tested yet!).  In /etc/gitlab/gitlab.rb you can configure a white-list of servers which do not get rate-limited:

'''
# gitlab_rails['rack_attack_git_basic_auth'] = {
#   'enabled' => true,
#   'ip_whitelist' => ["127.0.0.1"],
# ...
# }
'''
The  workaround could be comment out these lines and add the ip of your jenkins-server to the ip_whitelist.

**Comment by ace13** [comment]
Currently running with the default rack attack settings (as in, what gets written when nothing's set in `gitlab.rb`);
```
paths_to_be_protected = [
  "#{Rails.application.config.relative_url_root}/users/password",
  "#{Rails.application.config.relative_url_root}/users/sign_in",
  "#{Rails.application.config.relative_url_root}/api/#{API::API.version}/session.json",
  "#{Rails.application.config.relative_url_root}/api/#{API::API.version}/session",
  "#{Rails.application.config.relative_url_root}/users",
  "#{Rails.application.config.relative_url_root}/users/confirmation",
  "#{Rails.application.config.relative_url_root}/unsubscribes/",
  "#{Rails.application.config.relative_url_root}/import/github/personal_access_token",
]
```

None of those paths should be hit by the scanning from what I can see.

I assume that the Jenkins machine in question to add to the whitelist should be the build slave.

**Comment by Argelbargel** [comment]
I'm not sure, but i think scanning is done on the master, not the slaves. Only the checkout on/before build will happen on the slaves.

**Comment by ace13** [comment]
Got some additional information to add to this issue, found one of the projects that Jenkins tries to scan which always results in a 403 error.

The project in question only exists as a docker container repository, meaning it's bare of files and it has merge-requests disabled, which seems to lead to issues for the scan.

Here displayed through the power of cURL;
```
$ curl -H 'PRIVATE-TOKEN: AsdFghjKl-13A' https://gitlab.address/api/v3/projects/137/merge_requests?state=opened
{"message":"403 Forbidden"}
$ curl -H 'PRIVATE-TOKEN: AsdFghjKl-13A' https://gitlab.address/api/v3/projects/137
{"id":137..."container_registry_enabled":true,"issues_enabled":false,"merge_requests_enabled":false...
```

**Comment by Argelbargel** [comment]
Hi @ace13,

i think, i've fixed the problem when merge-requests are disabled (your last post). Still working on the rate-limiting...

**Comment by Argelbargel** [comment]
Hi @ace13,

i did some debugging and at least my gitlab does not send any headers containing information about the allowed request-rate. So i'm not sure how to limit the requests (the only way would be to configure them in the global jenkins settings). Did the whitelisting have any effect for your setup?

**Comment by ace13** [comment]
I think the thing I hit was the rack-attack limit, which only seems to count on requests that fail with 4XX error codes. So generally just not running any requests that are guaranteed to fail should help with that issue.

Not sure what the actual API rate-limit could be, so I'm unsure too on how to do a proper limit for that.

Didn't actually apply the whitelisting, instead just dropped the rescan interval so that it wouldn't hit the rack-attack limit. Didn't want to start hard-coding server FQDN/IPs into the config since we use Puppet.

**Comment by Argelbargel** [comment]
I do not see any clever way to swallow exceptions as the java-gitlab-api does just throws IOExceptions and there is no elegant way to check for the cause (e.g. 403 status code). So for now i'm just relying on not making requesting merge-requests when they are not enabled for a project.
