### ISSUE TITLE
Branch deletion prevents other builds in project

### ISSUE THREAD

**Issue by stewartwebb** [Argelbargel/gitlab-branch-source-plugin#89]
Getting a bug where the plugin will prevent building of any branch in a project if one branch that was previously available has been deleted. 

After deleting the branch from the Jenkins ui the problem is resolved.
```
ERROR: Failed to create or update a subproject ds/shared
java.util.NoSuchElementException: unknown branch develop/dmta
    at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.getBranch(GitLabAPI.java:101)
    at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveBranchRevision(SourceHeads.java:102)
    at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.observe(SourceHeads.java:231)
    at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveMergeRequests(SourceHeads.java:178)
    at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveAll(SourceHeads.java:162)
    at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieve(SourceHeads.java:69)
    at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMSource.retrieve(GitLabSCMSource.java:250)
    at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:357)
    at jenkins.scm.api.SCMSource.fetch(SCMSource.java:311)
    at jenkins.branch.MultiBranchProjectFactory$BySCMSourceCriteria.recognizes(MultiBranchProjectFactory.java:263)
    at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.recognizes(OrganizationFolder.java:1346)
    at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1361)
    at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitProject(SourceVisitor.java:65)
    at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:34)
    at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:25)
    at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator.visitSources(GitLabSCMNavigator.java:399)
    at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:458)
    at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
    at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
    at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:910)
```

**Comment by Argelbargel** [comment]
Please see the new, supported plugin at https://plugins.jenkins.io/gitlab-branch-source
